---
- name: Check container exists
  command: "docker ps"
  changed_when: false
  register: result

- name: Delete existing {{ item.key }} container
  become: yes
  docker_container:
    name: "{{ item.key }}"
    image: "{{ dkr_image }}"
    state: absent
    force_kill: true

- name: Start up Docker container {{ item.key }}
  docker_container:
    name: "{{ item.key }}"
    image: "{{ dkr_image }}"
    hostname: "{{ item.value.name }}"
    detach: yes
    tty: yes
    command: "{{ dkr_command | default('sleep infinity') }}"
    state: started
    exposed_ports: "[ {{ item.value.ports }} ]"
    privileged: "{{ dkr_privilege | default('no') }}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/pki/consumer:/etc/pki/consumer:ro
      - /etc/pki/entitlement:/etc/pki/entitlement:ro
#    volumes: "{{ dkr_volumes | default(omit) }}"

- name: Add container to inventory
  add_host:
    name: "{{ item.key }}"
    groups: "{{ host_group }}"
    ansible_connection: docker
  changed_when: false

- name: install sudo
  delegate_to: "{{ item.key }}"
  raw: test -e /bin/sudo || (yum install sudo -y)
  when: (dkr_image | search("rhel")) or
        (dkr_image | search("centos")) or
        (dkr_image | search("fedora"))
